import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  wrapper: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    flexDirection: 'column-reverse',
  },
  bg: {
    position: 'absolute',
    width: '100%',
    height: '100%',
  },
  container: {
    position: 'relative',
    backgroundColor: '#232227',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: 26,
  },
  imageLogo: {
    position: 'relative',
    width: 86,
    height: 86,
    marginTop: -40,
    marginBottom: 20,
  },
  textTip: {
    position: 'relative',
    fontSize: 15,
    color: '#ffffff',
    lineHeight: 21,
    textAlign: 'left',
    marginBottom: 20,
  },
  inputWrapper: {
    position: 'relative',
    height: 58,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 20,
    paddingLeft: 20,
    paddingRight: 20,
    backgroundColor: '#2F2E33',
    width: '100%',
    marginBottom: 20,
  },
  zone: {
    fontSize: 16,
    color: '#ffffff',
  },
  line: {
    height: 28,
    width: 1,
    backgroundColor: 'gray',
    marginLeft: 8,
    marginRight: 4,
  },
  inputNum: {
    height: '100%',
    flex: 1,
    color: '#ffffff',
    borderWidth: 0,
    fontSize: 16,
  },
  btnCode: {
    width: 100,
    height: 34,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#ffffff',
    fontSize: 14,
    lineHeight: 16,
    backgroundColor: '#3C3B3B',
    borderRadius: 20,
  },
  btnLogin: {
    width: '100%',
    height: 51,
    // display: 'flex',
    // alignItems: 'center',
    // justifyContent: 'center',
    backgroundColor: '#9AFC1E',
    borderRadius: 20,
    color: 'black',
    fontSize: 16,
    lineHeight: 51,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 40,
  },
  otherLoginWay: {
    color: '#ffffff',
    fontWeight: '500',
    fontSize: 16,
    marginBottom: 20,
  },
  google: {
    width: '100%',
    height: 51,
    borderRadius: 20,
    color: 'white',
    fontSize: 16,
    lineHeight: 51,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 40,
    borderColor: '#ffffff',
    borderWidth: 1,
  },
  loginTipWrapper: {
    display: 'flex',
    flexDirection: 'row',
  },
  loginTip: {
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '500',
    color: 'white',
  },
  item: {
    marginLeft: 10,
    fontSize: 16,
    lineHeight: 18,
    fontWeight: '500',
    color: 'white',
    textDecorationLine: 'underline',
  },
});
